version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rrud
      POSTGRES_PASSWORD: rrud
      POSTGRES_DB: rrud
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:v1.6
    ports:
      - "7700:7700"
    environment:
      MEILI_ENV: development
    volumes:
      - meilidata:/meili_data

  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
    volumes:
      - qdrantdata:/qdrant/storage

volumes:
  pgdata:
  meilidata:
  qdrantdata:
